In [21]:
import numpy as np

In [47]:
#question1
def calculate(arr2):
    print("Average of the last row:",arr2[11].mean())
    print("Minimum of the last row:",arr2[11].min())
    print("Maximum of the last row:",arr2[11].max())
    count =0
    for i in arr2[11]:
        if(i%2==0):
            count+=1
    print("No of even in last row",count)

         


arr=np.random.randint(1,100,60)
arr2 =arr.reshape(12,5)
print("Array is:")
print(arr2)
calculate(arr2)


Array is:
[[62 98 37 31 59]
 [58 96 54 56 48]
 [23 94 80 58  5]
 [31 19 28 65 36]
 [57 12  7 47 21]
 [26 74 15 53 89]
 [59 26 45 88 27]
 [74 99 68 57 13]
 [55 51 15 34 94]
 [48 56 99 93 28]
 [44 22 89  5 66]
 [18 68 25 87 73]]
Average of the last row: 54.2
Minimum of the last row: 18
Maximum of the last row: 87
No of even in last row 2


In [26]:
#question2
arr1=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(arr1[:,-1:-4:-1])


[[3 2 1]
 [6 5 4]
 [9 8 7]]
