In [6]:
#QUESTION 1
import numpy as n
arr =n.random.random((12,5))
print(arr)
print('The last row of the array is:',arr[11:12])
arr[11]=[1.78,2.56,3.333,4.43,5.8796]
print('After updating the last row array becomes:')
print(arr)



[[0.38820328 0.81137946 0.25540975 0.32877719 0.71378759]
 [0.0548677  0.95892328 0.67868499 0.50626228 0.57202246]
 [0.49792979 0.91920834 0.38898736 0.66748341 0.38788685]
 [0.45287305 0.29741708 0.34614468 0.25140469 0.90472754]
 [0.48019783 0.0334919  0.85664283 0.75360244 0.36540789]
 [0.40641215 0.36662385 0.55914815 0.72166251 0.52527533]
 [0.52173823 0.47856105 0.8855408  0.31667365 0.06154511]
 [0.61642588 0.75998654 0.15924204 0.57517228 0.34067799]
 [0.2676563  0.20767958 0.98250085 0.01057888 0.64563639]
 [0.95700925 0.13200145 0.67085767 0.37921036 0.35469975]
 [0.16356711 0.56376066 0.81894514 0.74820461 0.17267969]
 [0.58903347 0.50123299 0.39941796 0.95536879 0.04030878]]
The last row of the array is: [[0.58903347 0.50123299 0.39941796 0.95536879 0.04030878]]
After updating the last row array becomes:
[[0.38820328 0.81137946 0.25540975 0.32877719 0.71378759]
 [0.0548677  0.95892328 0.67868499 0.50626228 0.57202246]
 [0.49792979 0.91920834 0.38898736 0.66748341 0.3878868

In [7]:
#QUESTION 2
import numpy as n
arr2 = n.random.randint(1,60,60)
arr3=arr2.reshape(12,5)
print(arr3)
i =0
for row in arr3:
    print('The maximun value in row ',i,':',max(row))
    print('The minimum value in row ',i,':',min(row))
    i+=1

[[50  1 28 22 47]
 [37 12  1 15 37]
 [22  1  5  9 31]
 [24 26 23 56 20]
 [54 56 29 22 57]
 [30 53 15 29 50]
 [40 54 14 20 55]
 [25 43 38 29 58]
 [39 11 32 34 35]
 [49 40 47 36 33]
 [19 44 10  5  3]
 [47 57 15  1 10]]
The maximun value in row  0 : 50
The minimum value in row  0 : 1
The maximun value in row  1 : 37
The minimum value in row  1 : 1
The maximun value in row  2 : 31
The minimum value in row  2 : 1
The maximun value in row  3 : 56
The minimum value in row  3 : 20
The maximun value in row  4 : 57
The minimum value in row  4 : 22
The maximun value in row  5 : 53
The minimum value in row  5 : 15
The maximun value in row  6 : 55
The minimum value in row  6 : 14
The maximun value in row  7 : 58
The minimum value in row  7 : 25
The maximun value in row  8 : 39
The minimum value in row  8 : 11
The maximun value in row  9 : 49
The minimum value in row  9 : 33
The maximun value in row  10 : 44
The minimum value in row  10 : 3
The maximun value in row  11 : 57
The minimum value in row 